export default {
    BLANK : 8,
    BLANK_TEXTURE : 9,
    BLANK_SPECIAL : 10,

    CORNER_TOP_LEFT : 4,
    CORNER_TOP_RIGHT : 5,
    CORNER_BOTTOM_RIGHT : 6,
    CORNER_BOTTOM_LEFT : 7,    
    WALL_TOP : 0,
    WALL_LEFT : 1,
    WALL_BOTTOM : 2,
    WALL_RIGHT : 3,    
    DOOR_HOR_MIDDLE : 8,
    DOOR_HOR_LEFT : 8,
    DOOR_HOR_RIGHT : 8,
    DOOR_VER_MIDDLE : 8,
    DOOR_VER_TOP : 8,
    DOOR_VER_BOTTOM : 8
}